#!/usr/bin/env python3
"""Stage 5: Write photos to Photos.app albums based on assignments.csv + renames.csv.

Reads:
  metadata/assignments.csv   — uuid -> album (from Stage 3)
  metadata/renames.csv       — current_album, new_album, enabled (1/0)
                                 Yves edits this after review.
                                 Defaults are autogenerated by `--init`.

Modes:
  --init     Generate a default renames.csv from assignments.csv.
              Seed albums + clusters pre-filled; Yves edits new_album.
  --dry-run  Print what would be written; no Photos.app changes.
  --write    Actually create albums and add photos via osxphotos.

Safety:
  - Never deletes albums or photos.
  - Never removes a photo from an existing album.
  - Only ADDS photos to (possibly new) target albums.
  - Skips rows where enabled != "1".
  - Photos already in the target album are silently kept (osxphotos no-op).
  - "Thrash" is a local-only review marker — NEVER written to Photos.app.
"""
import argparse
import csv
import logging
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path.home() / "photo-sort"
ASSIGN_CSV = ROOT / "metadata" / "assignments.csv"

# Albums that are local-only review markers — never written to Photos.app
WRITE_SKIP = {"Thrash"}
RENAMES_CSV = ROOT / "metadata" / "renames.csv"
LOG_PATH = ROOT / "logs" / "05_write.log"

LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    handlers=[logging.FileHandler(LOG_PATH, mode="a"), logging.StreamHandler(sys.stdout)],
)
log = logging.getLogger("write")


def load_assignments():
    album_to_uids = defaultdict(list)
    with ASSIGN_CSV.open() as f:
        for r in csv.DictReader(f):
            album_to_uids[r["album"]].append(r["uuid"])
    return album_to_uids


def init_renames():
    """Pre-fill renames.csv with one row per current album.
       Yves fills the `new_album` column.
       Convention: empty `new_album` means SKIP (treated as enabled=0).
       Pre-filled defaults: seed albums identity-mapped; clusters left blank for Yves.
    """
    if RENAMES_CSV.exists():
        log.warning(f"{RENAMES_CSV} already exists — refusing to overwrite. Edit by hand.")
        return
    album_to_uids = load_assignments()
    # Sort: seeds first, clusters by size desc, Unsortiert last
    SEED_ORDER = ["Pornografie", "Pornografie-unsure", "Nacktheit", "Nacktheit-unsure",
                  "Motorrad-Werkstatt", "Motorrad-Werkstatt-unsure",
                  "Aquarium", "Aquarium-unsure",
                  "Garten", "Garten-unsure"]

    def key(item):
        a, uids = item
        if a in SEED_ORDER:
            return (0, SEED_ORDER.index(a))
        if a == "Unsortiert":
            return (3, 0)
        if a.startswith("Cluster-"):
            return (1, -len(uids))
        return (2, -len(uids))

    rows = sorted(album_to_uids.items(), key=key)
    with RENAMES_CSV.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["current_album", "count", "new_album", "enabled", "notes"])
        for a, uids in rows:
            default_new = a if not a.startswith("Cluster-") and a != "Unsortiert" else ""
            default_enabled = "1" if default_new else "0"
            w.writerow([a, len(uids), default_new, default_enabled, ""])
    log.info(f"Wrote {RENAMES_CSV}. Edit the `new_album` column, then run `--dry-run`.")


def load_renames():
    if not RENAMES_CSV.exists():
        log.error(f"{RENAMES_CSV} missing. Run with --init first.")
        sys.exit(2)
    mapping = {}
    with RENAMES_CSV.open() as f:
        for r in csv.DictReader(f):
            if r.get("enabled", "0").strip() != "1":
                continue
            new = r.get("new_album", "").strip()
            if not new:
                continue
            mapping[r["current_album"]] = new
    return mapping


def osxphotos_add(album_name: str, uuids: list, write: bool):
    """Use `osxphotos run` would need a Python script. Simpler: build a small inline command.
       We call osxphotos's `albums --add` capability via a helper script.
    """
    # Use `osxphotos albums` CLI if available, else fall back to PhotoKit via PhotosLibrary in venv.
    # Easiest path: call `osxphotos` to add photos to album.
    # osxphotos has `osxphotos add-to-album --album NAME --uuid UUID ...`
    # but we batch via a temp file with UUIDs.
    if not uuids:
        return
    log.info(f"  [{'WRITE' if write else 'DRY'}] album={album_name!r}  +{len(uuids)} photos")
    if not write:
        return
    # Write UUIDs to temp file
    tmp = ROOT / "logs" / "_tmp_uuids.txt"
    tmp.write_text("\n".join(uuids))
    # Invoke osxphotos via the pipx venv that has Photos access
    osx = Path.home() / ".local" / "bin" / "osxphotos"
    # We need a small Python helper because osxphotos CLI doesn't have a direct
    # "add-to-album" command in 0.75. Use photoscript via osxphotos venv.
    helper = ROOT / "_add_to_album_helper.py"
    helper.write_text(_ADD_HELPER_SRC)
    osx_python = Path.home() / ".local" / "pipx" / "venvs" / "osxphotos" / "bin" / "python"
    rc = subprocess.run(
        [str(osx_python), str(helper), album_name, str(tmp)],
        capture_output=True, text=True
    )
    if rc.returncode != 0:
        log.error(f"    helper failed: {rc.stderr[:500]}")
    else:
        log.info(f"    {rc.stdout.strip()}")


_ADD_HELPER_SRC = '''#!/usr/bin/env python3
"""Helper: add UUIDs to a named Photos.app album. Creates album if missing."""
import sys
from pathlib import Path
try:
    import photoscript
except ImportError:
    print("ERROR: photoscript not installed in osxphotos venv. Run: pipx inject osxphotos photoscript")
    sys.exit(2)

album_name = sys.argv[1]
uuid_file = Path(sys.argv[2])
uuids = [u.strip() for u in uuid_file.read_text().splitlines() if u.strip()]

lib = photoscript.PhotosLibrary()

# find or create album
album = None
for a in lib.albums():
    if a.title == album_name:
        album = a
        break
if album is None:
    album = lib.create_album(album_name)
    print(f"created album {album_name!r}")
else:
    print(f"using existing album {album_name!r}")

# Collect Photo objects by uuid (in chunks to avoid AppleScript timeout)
CHUNK = 200
added = 0
errors = 0
for i in range(0, len(uuids), CHUNK):
    batch = uuids[i:i+CHUNK]
    try:
        photos = [photoscript.Photo(u) for u in batch]
        album.add(photos)
        added += len(photos)
    except Exception as e:
        errors += 1
        print(f"chunk {i} failed: {e}")
print(f"added {added}/{len(uuids)} (errors {errors})")
'''


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--init", action="store_true", help="Generate default renames.csv")
    p.add_argument("--dry-run", action="store_true", help="Print plan, no writes")
    p.add_argument("--write", action="store_true", help="Actually write to Photos.app")
    args = p.parse_args()

    if args.init:
        init_renames()
        return

    if not (args.dry_run or args.write):
        p.error("specify --init, --dry-run, or --write")

    if args.write:
        log.warning("=== WRITE MODE — will create/modify Photos.app albums ===")
        log.warning("    iCloud will sync these albums to all your devices.")

    rename_map = load_renames()
    log.info(f"Loaded rename map: {len(rename_map)} albums enabled")
    album_to_uids = load_assignments()

    # Merge: target_album -> list of uuids (deduplicated)
    target_to_uids = defaultdict(set)
    for src, uids in album_to_uids.items():
        if src in rename_map:
            target_to_uids[rename_map[src]].update(uids)

    log.info(f"Total target albums: {len(target_to_uids)}")
    log.info(f"Total unique photos to add: {len(set.union(*target_to_uids.values())) if target_to_uids else 0}")

    for target in sorted(target_to_uids.keys()):
        if target in WRITE_SKIP:
            log.info(f"  [SKIP] {target!r} is a local-only marker — not written to Photos.app")
            continue
        osxphotos_add(target, sorted(target_to_uids[target]), write=args.write)

    log.info("Done.")


if __name__ == "__main__":
    main()
